version: "3.7"

services:

  ghost:
    image: ghost:latest
    ports:
      - "2019:2368"
    env_file: .env
    restart: always
    container_name: ghost
    working_dir: /var/lib/ghost
    volumes:
      - ./content:/var/lib/ghost/content